version: '3.7'

services:

  server:
    build:
      context: './server'
    networks: 
      - backend
    ports: 
      - "5000:5000"
    volumes:
      - ${PWD}/:/server
      - /server/node_modules
    container_name: server

  react:
    build:
      context: './server/react'
    networks: 
      - backend
    ports: 
      - "3000:3000"
    volumes:
      - ${PWD}/client/:/app
      - ${PWD}/client/build/:/app/build
    container_name: react

  mysql:
    image: mysql:5.6.40
    ports: 
      - 9000:9000
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=root
      - MYSQL_HOST=localhost
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=tshirt_shop
    container_name: mysql
    expose:
      - 9000

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
    ports:
      - 8000:80
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: rootpassword
        MYSQL_ROOT_PASSWORD: rootpassword
        PMA_HOST: mysql
    depends_on: 
      - mysql
    container_name: phpmyadmin
      
networks:
  # frontend:
  #   driver: bridge
  backend:
    driver: bridge